//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AqarSquare.Engine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUserEntity
    {
        public int ApplicationUserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public bool Status { get; set; }
        public bool IsActiveted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UserToken { get; set; }
    }
}
