//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AqarSquare.Engine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntertainmentReservationEntity
    {
        public int RestaurantReservationID { get; set; }
        public Nullable<int> EntertainmentID { get; set; }
        public Nullable<int> RestaurantID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<int> PersonCount { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public bool Indoor { get; set; }
        public bool Smoking { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Active { get; set; }
    
        public virtual EntertainmentEntity Entertainment { get; set; }
        public virtual RestaurantEntity Restaurant { get; set; }
    }
}
