//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alfardan.Engine.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AqarSquaresEntities : DbContext
    {
        public AqarSquaresEntities()
            : base("name=AqarSquaresEntities")
        {
          this.Configuration.LazyLoadingEnabled = true;
          this.Configuration.ProxyCreationEnabled = true;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<ContactForm> ContactForms { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<ContractType> ContractTypes { get; set; }
        public virtual DbSet<Image360> Image360 { get; set; }
        public virtual DbSet<ImageBalacony> ImageBalaconies { get; set; }
        public virtual DbSet<ImageBathroom> ImageBathrooms { get; set; }
        public virtual DbSet<ImageBedroom> ImageBedrooms { get; set; }
        public virtual DbSet<ImageGarden> ImageGardens { get; set; }
        public virtual DbSet<ImagePool> ImagePools { get; set; }
        public virtual DbSet<ImageReception> ImageReceptions { get; set; }
        public virtual DbSet<MainMenuBackend> MainMenuBackends { get; set; }
        public virtual DbSet<MainMenuFrontend> MainMenuFrontends { get; set; }
        public virtual DbSet<PriceAverage> PriceAverages { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<PropertyType> PropertyTypes { get; set; }
        public virtual DbSet<PropertyVeiwed> PropertyVeiweds { get; set; }
        public virtual DbSet<Square> Squares { get; set; }
        public virtual DbSet<SubMenuBackend> SubMenuBackends { get; set; }
        public virtual DbSet<SubMenuFrontend> SubMenuFrontends { get; set; }
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
        public virtual DbSet<TopTenProperty> TopTenProperties { get; set; }
        public virtual DbSet<UserFavourite> UserFavourites { get; set; }
        public virtual DbSet<UserRate> UserRates { get; set; }
    }
}
