//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AqarSquare.Engine.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConciergeEntity> ConciergeEntities { get; set; }
        public virtual DbSet<EntertainmentEntity> EntertainmentEntities { get; set; }
        public virtual DbSet<EntertainmentReservationEntity> EntertainmentReservationEntities { get; set; }
        public virtual DbSet<LimousineEntity> LimousineEntities { get; set; }
        public virtual DbSet<LocalBusinessPropertyEntity> LocalBusinessPropertyEntities { get; set; }
        public virtual DbSet<NotificationDeviceEntity> NotificationDeviceEntities { get; set; }
        public virtual DbSet<RestaurantEntity> RestaurantEntities { get; set; }
        public virtual DbSet<SpaEntity> SpaEntities { get; set; }
        public virtual DbSet<SpaReservationEntity> SpaReservationEntities { get; set; }
        public virtual DbSet<TreatmentEntity> TreatmentEntities { get; set; }
        public virtual DbSet<WellnessEntity> WellnessEntities { get; set; }
        public virtual DbSet<SystemUserEntity> SystemUserEntities { get; set; }
        public virtual DbSet<ReservationAvailabilityEntity> ReservationAvailabilityEntities1 { get; set; }
        public virtual DbSet<AboutEntity> AboutEntities { get; set; }
        public virtual DbSet<ApplicationUserEntity> ApplicationUserEntities { get; set; }
        public virtual DbSet<ContactEntity> ContactEntities { get; set; }
        public virtual DbSet<ItemEntity> ItemEntities { get; set; }
        public virtual DbSet<LookUpUApplicationUserEntity> LookUpUApplicationUserEntities { get; set; }
        public virtual DbSet<RestaurantCategoryEntity> RestaurantCategoryEntities { get; set; }
        public virtual DbSet<PropertyEntity> PropertyEntities { get; set; }
        public virtual DbSet<UserOrderEntity> UserOrderEntities { get; set; }
        public virtual DbSet<RestaurantWorkingHourEntity> RestaurantWorkingHourEntities { get; set; }
        public virtual DbSet<OrderReservationEntity> OrderReservationEntities { get; set; }
        public virtual DbSet<UnitEntity> UnitEntities { get; set; }
        public virtual DbSet<EntertainmentWorkingHourEntity> EntertainmentWorkingHourEntities { get; set; }
        public virtual DbSet<SpaWorkingHourEntity> SpaWorkingHourEntities { get; set; }
        public virtual DbSet<WellnessWorkingHourEntity> WellnessWorkingHourEntities { get; set; }
    }
}
