//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AqarSquare.Engine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemEntity
    {
        public int ItemId { get; set; }
        public string ItemTitleEn { get; set; }
        public string ItemTitleAr { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> Status { get; set; }
        public string DescriptionAr { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> RestaurantCategoryID { get; set; }
        public string DescriptionEn { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public byte[] ImageData { get; set; }
    
        public virtual RestaurantCategoryEntity RestaurantCategory { get; set; }
    }
}
