//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AqarSquare.Engine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LimousineEntity
    {
        public int LimousineID { get; set; }
        public string ImageURL { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionAr { get; set; }
        public byte[] ImageData { get; set; }
    }
}
