//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AqarSquare.Engine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalBusinessPropertyEntity
    {
        public LocalBusinessPropertyEntity()
        {
            this.Units = new HashSet<UnitEntity>();
        }
    
        public int BusinessPropertyID { get; set; }
        public string TitleEn { get; set; }
        public string TitleAr { get; set; }
        public string ImageURL { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionAr { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public int RestaurantId { get; set; }
        public byte[] ImageData { get; set; }
    
        public virtual RestaurantEntity Restaurant { get; set; }
        public virtual ICollection<UnitEntity> Units { get; set; }
    }
}
