//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AqarSquare.Engine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationDeviceEntity
    {
        public int NotificationDeviceID { get; set; }
        public AqarSquare.Engine.Devices DeviceType { get; set; }
        public string RegistrationID { get; set; }
        public string DeviceID { get; set; }
    }
}
