//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AqarSquare.Engine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderReservationEntity
    {
        public int OrderReservationId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> ItemQuantity { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public int UserOrderId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual UserOrderEntity UserOrder { get; set; }
    }
}
