//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AqarSquare.Engine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyEntity
    {
        public int PropertyId { get; set; }
        public string PropertyNameEn { get; set; }
        public string PropertyNameAr { get; set; }
        public int RestaurantId { get; set; }
    
        public virtual RestaurantEntity Restaurant { get; set; }
    }
}
