//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AqarSquare.Engine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationAvailabilityEntity
    {
        public int ID { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public int Availability { get; set; }
        public int RestaurantID { get; set; }
    }
}
