//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AqarSquare.Engine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantEntity
    {
        public RestaurantEntity()
        {
            this.Entertainments = new HashSet<EntertainmentEntity>();
            this.EntertainmentReservations = new HashSet<EntertainmentReservationEntity>();
            this.LocalBusinessProperties = new HashSet<LocalBusinessPropertyEntity>();
            this.RestaurantCategories = new HashSet<RestaurantCategoryEntity>();
        }
    
        public int RestaurantID { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public string PhoneNo { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public bool HasReservation { get; set; }
        public AqarSquare.Engine.IntegrationTypes IntegrationType { get; set; }
        public string Email { get; set; }
        public Nullable<int> AvailableSeats { get; set; }
        public Nullable<int> MinimumAvailability { get; set; }
        public Nullable<int> InitialAvailability { get; set; }
        public Nullable<bool> Smoking { get; set; }
        public Nullable<bool> InDoor { get; set; }
        public string EmailTemplate { get; set; }
    
        public virtual ICollection<EntertainmentEntity> Entertainments { get; set; }
        public virtual ICollection<EntertainmentReservationEntity> EntertainmentReservations { get; set; }
        public virtual ICollection<LocalBusinessPropertyEntity> LocalBusinessProperties { get; set; }
        public virtual ICollection<RestaurantCategoryEntity> RestaurantCategories { get; set; }
    }
}
