//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AqarSquare.Engine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantCategoryEntity
    {
        public int RestaurantCategoryID { get; set; }
        public string CategoryTitleEn { get; set; }
        public string CategoryTitleAr { get; set; }
        public Nullable<int> RestaurantID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> OrderBy { get; set; }
    
        public virtual RestaurantEntity Restaurant { get; set; }
    }
}
