//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AqarSquare.Engine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpaEntity
    {
        public SpaEntity()
        {
            this.SpaReservations = new HashSet<SpaReservationEntity>();
            this.Wellnesses = new HashSet<WellnessEntity>();
            this.Treatments = new HashSet<TreatmentEntity>();
        }
    
        public int SpaID { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public string BriefEn { get; set; }
        public string BriefAr { get; set; }
        public string PhoneNo { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public bool HasReservation { get; set; }
        public AqarSquare.Engine.IntegrationTypes IntegrationType { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<SpaReservationEntity> SpaReservations { get; set; }
        public virtual ICollection<WellnessEntity> Wellnesses { get; set; }
        public virtual ICollection<TreatmentEntity> Treatments { get; set; }
    }
}
