//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AqarSquare.Engine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpaReservationEntity
    {
        public int SpaReservationID { get; set; }
        public Nullable<int> WellnessID { get; set; }
        public Nullable<int> SpaID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<int> TreatmentID { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public Nullable<AqarSquare.Engine.Gender> Gender { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Active { get; set; }
    
        public virtual SpaEntity Spa { get; set; }
        public virtual TreatmentEntity Treatment { get; set; }
        public virtual WellnessEntity Wellness { get; set; }
    }
}
