//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AqarSquare.Engine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUserEntity
    {
        public int SystemUserID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public bool ManageEntertainments { get; set; }
        public bool ManageWellnesses { get; set; }
        public bool ManageLocalBusinessDirectories { get; set; }
        public bool ManageLimousine { get; set; }
        public bool ManageConcierge { get; set; }
        public bool ManagePushNotifications { get; set; }
        public bool ManageSystemUsers { get; set; }
        public Nullable<bool> ManageUnit { get; set; }
        public Nullable<bool> ManageAbout { get; set; }
        public Nullable<bool> ManageContact { get; set; }
        public Nullable<bool> ManageApplicationUser { get; set; }
        public Nullable<bool> ManageCategoryResturant { get; set; }
        public Nullable<bool> ManageItem { get; set; }
        public Nullable<bool> ManageOrderReservation { get; set; }
    }
}
