//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AqarSquare.Engine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentEntity
    {
        public TreatmentEntity()
        {
            this.SpaReservations = new HashSet<SpaReservationEntity>();
            this.Spas = new HashSet<SpaEntity>();
        }
    
        public int TreatmentID { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public string BriefEn { get; set; }
        public string BriefAr { get; set; }
    
        public virtual ICollection<SpaReservationEntity> SpaReservations { get; set; }
        public virtual ICollection<SpaEntity> Spas { get; set; }
    }
}
