//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AqarSquare.Engine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitEntity
    {
        public int UnitId { get; set; }
        public string UnitNumber { get; set; }
        public int BusinessPropertyID { get; set; }
        public int ViewBy { get; set; }
    
        public virtual LocalBusinessPropertyEntity LocalBusinessProperty { get; set; }
    }
}
